---
- name: just a test playbook
  hosts: all
  gather_facts: false

  vars:
    foo: _bar2

  tasks:
    - name: Run yum update
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '9'   
