---
- name: Just a test playbook
  hosts: all
  gather_facts: false

  vars:
    foo: _bar2

  tasks:
    - name: Run dnf update
      ansible.builtin.dnf:
        name: "*"
        state: latest #noqa: package-latest
      when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '9'
