name: Ansible Lint  # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Example secret
    # - shell: bash
    #   run: |
    #     echo ${{secrets.ANSIBLE_VAULT_PASSWORD}} | sed 's/./& /g'

    # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v4.2.2

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint@main
